version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-sqs-lambda-dlq-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1m0305c74a7wb"
s3_prefix = "sam-sqs-lambda-dlq-example"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
